# **Pandas**

**Pandas** is a powerful **Python library for data manipulation and analysis.** It provides easy-to-use data structures and functions to work with structured data like tabular, time series, or matrix data.

**Pandas primarily provides two data structures: Series and DataFrame.**

**Series:** A one-dimensional labeled array capable of holding any data type.

**DataFrame:** A two-dimensional labeled data structure with columns of potentially different types.

In [1]:
import pandas as pd
import numpy as np

# **Pandas - Series**

**Series** in pandas is a fundamental data structure that represents a one-dimensional array of indexed data. It can hold any type of **data—integers, strings, floats, Python objects**, etc. The Series object is built on top of the NumPy array and is very similar to it but with additional capabilities like handling missing data. The indices of a pandas Series are more flexible than those in a simple NumPy array.

## <b> Creating a Series

In [2]:
s = pd.Series([1, 3, 5, 7, 9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64

**Key Attributes**

**Values:** The data in the Series.

**Index:** The index (labels) of each data point.

# **Common Methods of Series**

# Descriptive Statistics

* **s.describe():** Provides a quick summary of the data.

This method gives a statistical summary of the Series, including count, mean, standard deviation, minimum, maximum, and quartile values.

In [7]:
# Creating a Series
s = pd.Series([1, 3, 5, 7, 9, 5])

# Descriptive statistics
print(s.describe())

count    6.000000
mean     5.000000
std      2.828427
min      1.000000
25%      3.500000
50%      5.000000
75%      6.500000
max      9.000000
dtype: float64

In [8]:
s.mean()

5.0

In [9]:
s.median()

5.0

In [10]:
s.mode()

0    5
dtype: int64

In [11]:
s.std()

2.8284271247461903

In [13]:
s.min()

1

In [14]:
s.max()

9

## <b>Data Manipulation

**s.map(func):** Applies a function to each element in the Series.

In [15]:
s

0    1
1    3
2    5
3    7
4    9
5    5
dtype: int64

In [16]:
# Mapping function to double the values
doubled = s.map(lambda x: x * 2)
print(doubled)

0     2
1     6
2    10
3    14
4    18
5    10
dtype: int64

**s.apply(func):** Similar to map, but more flexible. (Can be used Data Frames as well, where as map is only for Series)

In [17]:
# Applying a function to calculate square root
sqrt = s.apply(lambda x: x ** 0.5)
print(sqrt)

0    1.000000
1    1.732051
2    2.236068
3    2.645751
4    3.000000
5    2.236068
dtype: float64

**s.sort_values():** Sorts the Series.

In [18]:
# Sorting the Series
sorted_s = s.sort_values()
print(sorted_s)

0    1
1    3
2    5
5    5
3    7
4    9
dtype: int64

**s.drop(labels):** Drops specified labels from the Series.

In [19]:
# Dropping the first element
dropped = s.drop(0)
print(dropped)

1    3
2    5
3    7
4    9
5    5
dtype: int64

In [20]:
print(s)

0    1
1    3
2    5
3    7
4    9
5    5
dtype: int64

## <b>Handling Missing Data

**s.isnull():** Checks for missing values, returns a Series of booleans.

In [21]:
# Checking for missing values
print(s.isnull())

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

**s.notnull():** Opposite of isnull().

In [22]:
# Checking for non-null values
print(s.notnull())

0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool

**s.fillna(value):** Fills missing values with a specified value.

In [23]:
# Create a Series with missing values
s = pd.Series([1, 2, np.nan, 4, np.nan])

# Print the Series
print(s)

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [24]:
# Filling missing values with 0
filled = s.fillna(9)
print(filled)

0    1.0
1    2.0
2    9.0
3    4.0
4    9.0
dtype: float64

**s.dropna():** Drops all rows that contain missing values.

In [25]:
# Creating a Series with missing values
s_with_missing = pd.Series([1, 2, None, 4, 5])

# Dropping missing values
dropped_missing = s_with_missing.dropna()
print(dropped_missing)

0    1.0
1    2.0
3    4.0
4    5.0
dtype: float64

## <b> Indexing, Slicing, and Filtering


<b> s.iloc[ ]: </b> Purely integer-location based indexing.

In [26]:
# Indexing by position
s = pd.Series([1, 3, 5, 7, 9])
print(s.iloc[0])  # First element
print(s.iloc[-1])  # Last element

1
9

**s.loc[ ]:** Label-based indexing.

In [27]:
# Indexing by label
print(s.loc[0])  # First element
print(s.loc[4])  # Last element

1
9

In [28]:
# Create a Series
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)
# Accessing elements using iloc
print(s.iloc[0])  # Access the first element
print(s.iloc[1:3])  # Access elements at positions 1 and 2 (exclusive of 3)

# Accessing elements using loc
print(s.loc['a'])  # Access the element with index label 'a'
print(s.loc['b':'c'])  # Access elements with index labels 'b' and 'c'

a    10
b    20
c    30
d    40
dtype: int64
10
b    20
c    30
dtype: int64
10
b    20
c    30
dtype: int64

**s[s > n]:** Filters and returns elements greater than n.

In [29]:
# Filtering elements greater than 5
filtered = s[s > 5]
print(filtered)

a    10
b    20
c    30
d    40
dtype: int64

## <b> Aggregation

**s.sum():** Sums up the values.

In [30]:
# Sum of the Series
print(s.sum())

100

**s.cumsum():** Cumulative sum.

In [31]:
# Cumulative sum of the Series
print(s)
print(s.cumsum())

a    10
b    20
c    30
d    40
dtype: int64
a     10
b     30
c     60
d    100
dtype: int64

**s.aggregate(func):** Aggregates using one or more operations.

In [32]:
# Aggregating using multiple operations
aggregated = s.aggregate(['sum', 'mean', 'std'])
print(aggregated)

sum     100.000000
mean     25.000000
std      12.909944
dtype: float64

## <b> Creating Data Frame

In [36]:
# Define data
data = {
    'Name': ['Mahender Reddy Narra', 'Vihaan', 'Akhil', 'Bharath', 'Charan', 'Shreya', 'Divyansh', 'Varun'],
    'Role': ['Founder', 'Growth Manager', 'Community Manager', 'Community Manager', 'Community Manager',
             'Designer', 'Coder', 'Public Relations Manager'],
    'Phone Number': ['111-111-1111', '222-222-2222', '333-333-3333', '444-444-4444',
                     '555-555-5555', '666-666-6666', '777-777-7777', '888-888-8888'],
    'Email': ['mahender.narra@gmail.com', 'vihaan@gmail.com', 'divyansh@gmail.com', 'varun@gmail.com',
              'akhil@gmail.com', 'shreya@gmail.com', 'varsha@gmail.com', 'varun@@gmail.com'],
    'Address': ['123, MG Road, Bangalore', '456, Brigade Road, Chennai', '789, Rajaji Nagar, Mumbai', '101, Indira Nagar, Delhi',
                '202, Koramangala, Hyderabad', '303, JP Nagar, Kolkata', '404, Electronic City, Pune', '505, HSR Layout, Ahmedabad'],
    'Blood Group': ['A+', 'B-', 'O+', 'AB+', 'A-', 'B+', 'O-', 'AB-']
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
df.head()

,Name,Role,Phone Number,Email,Address,Blood Group
0,Mahender Reddy Narra,Founder,111-111-1111,mahender.narra@gmail.com,"123, MG Road, Bangalore",A+
1,Vihaan,Growth Manager,222-222-2222,vihaan@gmail.com,"456, Brigade Road, Chennai",B-
2,Akhil,Community Manager,333-333-3333,divyansh@gmail.com,"789, Rajaji Nagar, Mumbai",O+
3,Bharath,Community Manager,444-444-4444,varun@gmail.com,"101, Indira Nagar, Delhi",AB+
4,Charan,Community Manager,555-555-5555,akhil@gmail.com,"202, Koramangala, Hyderabad",A-

In [37]:
df

,Name,Role,Phone Number,Email,Address,Blood Group
0,Mahender Reddy Narra,Founder,111-111-1111,mahender.narra@gmail.com,"123, MG Road, Bangalore",A+
1,Vihaan,Growth Manager,222-222-2222,vihaan@gmail.com,"456, Brigade Road, Chennai",B-
2,Akhil,Community Manager,333-333-3333,divyansh@gmail.com,"789, Rajaji Nagar, Mumbai",O+
3,Bharath,Community Manager,444-444-4444,varun@gmail.com,"101, Indira Nagar, Delhi",AB+
4,Charan,Community Manager,555-555-5555,akhil@gmail.com,"202, Koramangala, Hyderabad",A-
5,Shreya,Designer,666-666-6666,shreya@gmail.com,"303, JP Nagar, Kolkata",B+
6,Divyansh,Coder,777-777-7777,varsha@gmail.com,"404, Electronic City, Pune",O-
7,Varun,Public Relations Manager,888-888-8888,varun@@gmail.com,"505, HSR Layout, Ahmedabad",AB-

## <b> Merging Data Frames

In [40]:
# Team roles data
roles_data = {
    'Name': ['Mahender Reddy', 'Vihaan', 'Mahesh', 'Nikhil', 'Naveen', 'Shreya', 'Varsha', 'Varun Tej'],
    'Role': ['Founder', 'Growth Manager', 'Community Manager', 'Community Manager', 'Community Manager',
             'Course Designer', 'Course Designer', 'Public Relations Manager']
}

roles_df = pd.DataFrame(roles_data)

# Contact information data
contact_data = {
    'Name': ['Mahender Reddy', 'Vihaan',  'Mahesh', 'Nikhil', 'Naveen', 'Shreya', 'Varsha', 'Varun Tej'],
    'Phone Number': ['111-111-1111', '222-222-2222', '333-333-3333', '444-444-4444',
                     '555-555-5555', '666-666-6666', '777-777-7777', '888-888-8888'],
    'Email': ['nihar@masscoders.tech', 'vignesh@masscoders.tech', 'maheshwar@masscoders.tech', 'naman@masscoders.tech',
              'naveen@masscoders.tech', 'shreya@masscoders.tech', 'varsha@masscoders.tech', 'varun@masscoders.tech']
}

contact_df = pd.DataFrame(contact_data)

In [41]:
merged_df = pd.merge(roles_df, contact_df, on='Name')

In [42]:
merged_df

,Name,Role,Phone Number,Email
0,Mahender Reddy,Founder,111-111-1111,nihar@masscoders.tech
1,Vihaan,Growth Manager,222-222-2222,vignesh@masscoders.tech
2,Mahesh,Community Manager,333-333-3333,maheshwar@masscoders.tech
3,Nikhil,Community Manager,444-444-4444,naman@masscoders.tech
4,Naveen,Community Manager,555-555-5555,naveen@masscoders.tech
5,Shreya,Course Designer,666-666-6666,shreya@masscoders.tech
6,Varsha,Course Designer,777-777-7777,varsha@masscoders.tech
7,Varun Tej,Public Relations Manager,888-888-8888,varun@masscoders.tech

# **Importing Dataset**

Importing datasets into Pandas is straightforward, and Pandas supports various file formats like csv, xlsx, json, sql etc.

In [46]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [47]:
df = pd.read_csv(r'/content/drive/MyDrive/filmtv_movies.csv')

# Display the first few rows of the DataFrame to understand its structure and contents
df.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

The dataset contains information about movies, represented in a DataFrame structure.

**filmtv_id:** A unique identifier for each movie.

**title:** The title of the movie.

**year:** The release year of the movie.

**genre:** The genre of the movie.

**duration:** The duration of the movie in minutes.

**country:** The country where the movie was produced.

**directors:** Names of the directors of the movie.

**actors:** Names of the main actors in the movie.

**avg_vote, critics_vote, public_vote:** Average ratings from different sources.

**total_votes:** Total number of votes the movie received.

**description:** A short description of the movie plot.

**notes:** Additional notes or commentary about the movie.

**humor, rhythm, effort, tension, erotism:** Various attributes rated on a scale (probably from 0 to a maximum value, representing different aspects of the movie).

# **Pandas - DataFrame**

## <b> Properties of DataFrame

**df.head(n):**
The df.head(n) method is used to view the first n rows of the DataFrame. This is particularly useful for getting a quick snapshot of the data, especially to understand the structure and the types of data contained in each column. If you don't specify n, the default number of rows displayed is 5.

In [48]:
df.head(10)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
5,21,The Uranian Conspiracy,1978,Spy,117,"Italy, Germany, Israel","Gianfranco Baldanello, Menahem Golan","Fabio Testi, Janet Agren, Assaf Dayan, Siegfri...",4.8,3.50,6.0,5,Two Israeli secret agents discover that traffi...,"Action and chases for half of Europe, espionag...",1,2,0,2,0
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
7,23,Dead-Bang,1989,Crime,109,United States,John Frankenheimer,"Don Johnson, Penelope Ann Miller, William Fors...",6.0,6.00,6.0,27,"In the throes of a double murder, Jerry Beck, ...",When it comes to talking about mysterious plot...,0,2,0,2,1
8,24,A... come assassino,1966,Thriller,80,Italy,Ray Morrison (Angelo Dorigo),"Alan Steel, Mary Arden, Sergio Ciani, Ivano Da...",5.2,3.00,7.0,5,After a man's corpse is found by his niece in ...,Approximation and mediocrity in go-go.,1,2,0,1,0
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2

In [49]:
df.tail(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [50]:
df.shape  # no. of rows & columns

(41399, 19)

**df.columns:**
The df.columns attribute returns an Index object containing the column labels of the DataFrame. Knowing the column names is essential for accessing specific data in the DataFrame, performing analyses, and for data manipulation tasks like sorting, filtering, or applying functions to certain columns.

In [51]:
df.columns

Index(['filmtv_id', 'title', 'year', 'genre', 'duration', 'country',
       'directors', 'actors', 'avg_vote', 'critics_vote', 'public_vote',
       'total_votes', 'description', 'notes', 'humor', 'rhythm', 'effort',
       'tension', 'erotism'],
      dtype='object')

**Inspecting Data Types:** Each column in a DataFrame has a specific data type. Understanding these types is crucial for proper data manipulation

In [52]:
 # Display the data types of each column
df.dtypes

filmtv_id         int64
title            object
year              int64
genre            object
duration          int64
country          object
directors        object
actors           object
avg_vote        float64
critics_vote    float64
public_vote     float64
total_votes       int64
description      object
notes            object
humor             int64
rhythm            int64
effort            int64
tension           int64
erotism           int64
dtype: object

**Summary Statistics:** For numerical data, it's useful to get a sense of their central tendency and spread

In [53]:
# Display summary statistics for numerical columns
df.describe()

,filmtv_id,year,duration,avg_vote,critics_vote,public_vote,total_votes,humor,rhythm,effort,tension,erotism
count,41399.000000,41399.000000,41399.000000,41399.000000,36703.000000,41205.000000,41399.000000,41399.000000,41399.000000,41399.000000,41399.000000,41399.000000
mean,57746.410179,1993.505302,100.537163,5.801522,5.796077,5.924135,36.986763,0.577381,1.345347,0.684847,0.919153,0.309814
std,59962.095730,23.685612,27.260962,1.403861,1.593062,1.480112,69.386853,0.899402,1.154829,1.112334,1.095410,0.645930
min,2.000000,1897.000000,41.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15857.000000,1976.000000,90.000000,4.800000,4.670000,5.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,36266.000000,2001.000000,96.000000,5.900000,6.000000,6.000000,12.000000,0.000000,2.000000,0.000000,0.000000,0.000000
75%,70935.000000,2013.000000,107.000000,6.900000,7.000000,7.000000,36.000000,1.000000,2.000000,1.000000,2.000000,0.000000
max,232920.000000,2023.000000,1525.000000,10.000000,10.000000,10.000000,1082.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [54]:
# Display summary statistics for numerical columns
df.describe().T

,count,mean,std,min,25%,50%,75%,max
filmtv_id,41399.0,57746.410179,59962.095730,2.0,15857.00,36266.0,70935.0,232920.0
year,41399.0,1993.505302,23.685612,1897.0,1976.00,2001.0,2013.0,2023.0
duration,41399.0,100.537163,27.260962,41.0,90.00,96.0,107.0,1525.0
avg_vote,41399.0,5.801522,1.403861,1.0,4.80,5.9,6.9,10.0
critics_vote,36703.0,5.796077,1.593062,1.0,4.67,6.0,7.0,10.0
public_vote,41205.0,5.924135,1.480112,1.0,5.00,6.0,7.0,10.0
total_votes,41399.0,36.986763,69.386853,1.0,5.00,12.0,36.0,1082.0
humor,41399.0,0.577381,0.899402,0.0,0.00,0.0,1.0,5.0
rhythm,41399.0,1.345347,1.154829,0.0,0.00,2.0,2.0,5.0
effort,41399.0,0.684847,1.112334,0.0,0.00,0.0,1.0,5.0
tension,41399.0,0.919153,1.095410,0.0,0.00,0.0,2.0,5.0
erotism,41399.0,0.309814,0.645930,0.0,0.00,0.0,0.0,5.0

### <b> Accessing and Filtering: </b>

**df.loc:**
The df.loc method is used for label-based indexing, meaning you can access rows and columns using their labels (i.e., index names and column names). It allows for selecting a subset of rows and columns from a DataFrame with powerful and flexible slicing, indexing, and filtering options.

In [55]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [56]:
# Selecting all rows and a specific column by label
titles = df.loc[:, 'title']
titles

0        Bugs Bunny's Third Movie: 1001 Rabbit Tales
1                          18 anni tra una settimana
2                                   Ride a Wild Pony
3                                              Diner
4                    A che servono questi quattrini?
                            ...
41394                             Gold Digger Killer
41395                            Addio al nubilato 2
41396                                    Konferensen
41397                                      Ballelina
41398                      Invitación a un Asesinato
Name: title, Length: 41399, dtype: object

In [57]:
# Selecting a range of rows and multiple columns by labels
subset = df.loc[10:20, ['title', 'year', 'genre']]
subset

                                   title  year        genre
10             A Ghentar si muore facile  1968    Adventure
11               Sleeping with the Enemy  1990        Drama
12                   In Bed With Madonna  1990  Documentary
13                    Bowery at Midnight  1942       Horror
14  A mezzanotte va la ronda del piacere  1975       Comedy
15                          Mr. Majestyk  1974       Action
16                          Warning Sign  1985       Action
17                      About Last Night  1986       Comedy
18                             Fail-Safe  1964        Drama
19                      Some Like It Hot  1959       Comedy
20                    A qualsiasi prezzo  1968    Adventure

In [58]:
# Conditional selection using a boolean array
dramas = df.loc[df['genre'] == 'Drama']
dramas

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
11,32,Sleeping with the Enemy,1990,Drama,96,United States,Joseph Ruben,"Julia Roberts, Patrick Bergin, Kevin Anderson,...",5.0,4.33,6.0,111,Martin and Laura Burney have been married for ...,"Some twist is actually well placed, but from a...",1,3,2,3,1
18,49,Fail-Safe,1964,Drama,110,United States,Sidney Lumet,"Henry Fonda, Dan O'Herlihy, Walter Matthau, Do...",8.2,8.20,8.0,73,When the US strategic air command is alerted t...,"With this film Lumet returns great, after a pe...",0,3,3,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41368,229838,Tereddüt Çizgisi,2023,Drama,84,"Turkey, France, Romania, Spain",Selman Nacar,"Tülin Özen, Görkem Ipek",7.0,7.00,7.0,3,All over a day. A criminal lawyer is awaiting ...,NaN,0,0,0,0,0
41370,229865,Stolen,2023,Drama,92,India,Karan Tejpal,"Abhishek Banerjee, Harish Khanna, Mia Maelzer,...",5.3,6.00,5.0,4,"The five -month daughter of Jhumpa Mahato, poo...",NaN,0,0,0,0,0
41371,229881,Árni,2023,Drama,103,Hungary,Dorka Vermes,"Péter Turi, Andrea Spolarics",5.3,6.00,5.0,3,A lone nomad who works for an itinerant circus...,NaN,0,0,0,0,0
41372,229883,Kanata no uta,2023,Drama,84,Japan,Kyoshi Sugita,"An Ogawa, Yûko Nakamura, Hidekazu Mashima",5.5,5.00,6.0,3,"The twenty -five year old Haru, committed in a...",NaN,0,0,0,0,0
41390,232203,Mes petites amoureuses,1974,Drama,123,France,Jean Eustache,"Martin Loeb, Jacqueline Dufranne, Jacques Roma...",8.3,8.50,8.0,3,Daniel is a silent boy who observes girls with...,NaN,0,0,0,0,0

In [59]:
multiple_condition = df.loc[(df['genre'] == 'Drama') & (df['avg_vote']>7.0)]
multiple_condition

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
18,49,Fail-Safe,1964,Drama,110,United States,Sidney Lumet,"Henry Fonda, Dan O'Herlihy, Walter Matthau, Do...",8.2,8.20,8.0,73,When the US strategic air command is alerted t...,"With this film Lumet returns great, after a pe...",0,3,3,3,0
30,70,Can You Feel Me Dancing?,1986,Drama,120,United States,Michael Miller,"Justine Bateman, Jason Bateman, Max Gail, Joe ...",8.0,6.00,10.0,3,"Karin Nichols, blind since birth, no longer st...","Based on a true story, it is a film for televi...",0,2,2,0,0
44,92,Accattone,1961,Drama,120,Italy,Pier Paolo Pasolini,"Franco Citti, Franca Pasut, Adriana Asti, Paol...",8.4,8.81,8.0,299,"Story of a drifter, Accattone, who drags an em...",After seeing the first dailies Federico Fellin...,1,3,3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41320,226639,Sambizanga,1972,Drama,97,"Angola, France",Sarah Maldoror,"Elisa Andrade, Jean M'Vondo, Dino Abelino, Ben...",7.5,7.50,8.0,4,"Angola, 1961. Domingos Xavier, an anti -coloni...",Taken from a true story told in the book in Vi...,0,0,0,0,0
41349,229784,The Burial,2023,Drama,126,United States,Maggie Betts,"Bill Camp, Jamie Foxx, Tommy Lee Jones, Alan R...",7.3,NaN,7.0,10,"With the help of two lawyers, a family struggl...",NaN,0,1,1,1,0
41355,229808,Aku wa sonzai shinai,2023,Drama,106,Japan,Ryûsuke Hamaguchi,"Hitoshi Omika, Ryo Nishikawa, Ryuji Kosaka, Ay...",7.2,7.00,7.0,9,"Takumi and his daughter Hana live in Mizubiki,...",NaN,0,0,0,0,0
41366,229832,Magyarázat mindenre,2023,Drama,151,"Hungary, Slovakia",Gábor Reisz,"Adonyi-Walsh Gáspár, István Znamenák, András R...",7.3,7.33,7.0,6,"A realistic portrait of a divided country, Hun...",NaN,0,0,0,0,0
41390,232203,Mes petites amoureuses,1974,Drama,123,France,Jean Eustache,"Martin Loeb, Jacqueline Dufranne, Jacques Roma...",8.3,8.50,8.0,3,Daniel is a silent boy who observes girls with...,NaN,0,0,0,0,0

**df.iloc:**
While df.loc uses labels for indexing, df.iloc allows for integer-based indexing. You use df.iloc to access rows and columns by their integer positions, which makes it useful when you need to access data by its position in the DataFrame.

In [60]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [61]:
# Selecting a single row from the DataFrame
single_row = df.iloc[0]
single_row

filmtv_id                                                       2
title                 Bugs Bunny's Third Movie: 1001 Rabbit Tales
year                                                         1982
genre                                                   Animation
duration                                                       76
country                                             United States
directors                    David Detiege, Art Davis, Bill Perez
actors                                                        NaN
avg_vote                                                      7.7
critics_vote                                                  8.0
public_vote                                                   7.0
total_votes                                                    22
description     With two protruding front teeth, a slightly sl...
notes           These are many small independent stories, whic...
humor                                                           3
rhythm                                                          3
effort                                                          0
tension                                                         0
erotism                                                         0
Name: 0, dtype: object

In [62]:
# Selecting a specific row and columns by integer indices
specific_data = df.iloc[10, [1, 2, 3]]  # row at index 10 and columns at indices 1, 2, and 3
specific_data

title    A Ghentar si muore facile
year                          1968
genre                    Adventure
Name: 10, dtype: object

In [63]:
# Slicing to get multiple rows and columns
multi_slice = df.iloc[10:15, 0:4]  # Rows 10 to 14 and columns 0 to 3
multi_slice

    filmtv_id                                 title  year        genre
10         30             A Ghentar si muore facile  1968    Adventure
11         32               Sleeping with the Enemy  1990        Drama
12         34                   In Bed With Madonna  1990  Documentary
13         36                    Bowery at Midnight  1942       Horror
14         37  A mezzanotte va la ronda del piacere  1975       Comedy

**df.at:**
df.at is designed to access a single value for a row/column label pair. It is very similar to df.loc for accessing scalar values but is optimized for faster access when you only need to get or set a single value in a DataFrame.

In [64]:
# Access a specific single value using row label and column name
title_of_first_movie = df.at[0, 'title']
title_of_first_movie

"Bugs Bunny's Third Movie: 1001 Rabbit Tales"

**Filtering Based on Criteria:**
Filtering data based on specific criteria is a common operation in data analysis. Pandas provides several methods to perform these operations, often using boolean indexing.

In [65]:
# Filter movies released after 2010
recent_movies = df[df['year'] > 2010]
recent_movies

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
22817,39955,The Tree of Life,2011,Drama,138,United States,Terrence Malick,"Brad Pitt, Sean Penn, Jessica Chastain, Tye Sh...",7.4,7.43,7.0,476,"Jack, an eleven-year-old boy, lives in the Mid...","Beauty passes through cinema: the director, as...",0,2,4,2,0
23725,41448,Season of the Witch,2011,Adventure,95,United States,Dominic Sena,"Nicolas Cage, Claire Foy, Ron Perlman, Stephen...",4.3,4.13,4.0,153,"During the fourteenth century, when the black ...",Thrown to the wind the attempts to build a bar...,1,2,1,3,0
24186,42398,Restless,2011,Drama,95,United States,Gus Van Sant,"Mia Wasikowska, Schuyler Fisk, Jane Adams, Lus...",6.9,6.59,7.0,151,Enoch is a 17-year-old who lost both parents a...,The director of Last Days returns to spy on th...,2,2,3,1,0
24426,42847,Qualunquemente,2011,Grotesque,96,Italy,Giulio Manfredonia,"Antonio Albanese, Sergio Rubini, Lorenza Indov...",5.6,5.65,6.0,291,Cetto La Qualunque (Albanese) returns to Italy...,The grotesque and at times effective mask rema...,4,3,3,1,1
24427,42848,Una sconfinata giovinezza,2011,Drama,98,Italy,Pupi Avati,"Fabrizio Bentivoglio, Francesca Neri, Serena G...",6.7,6.60,7.0,95,Lino Settembre and his wife Chicca lead a peac...,"Written with the taste of a novelist's plot, i...",2,2,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [66]:
# Movies with a high public vote and specific genre
highly_rated_thrillers = df[(df['public_vote'] >= 8) & (df['genre'] == 'Thriller')]
highly_rated_thrillers

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
21,54,Johnny O'Clock,1947,Thriller,95,United States,Robert Rossen,"Dick Powell, Evelyn Keyes, Lee J. Cobb, Ellen ...",7.8,8.00,8.0,20,Johnny O'Clock (Powell) is a minority partner ...,Columbia took advantage of Dick Powell's recen...,1,3,1,3,1
27,67,You'll Like My Mother,1973,Thriller,94,United States,Lamont Johnson,"Patty Duke, Rosemary Murphy, Richard Thomas, S...",7.8,8.00,8.0,6,"After her husband's death, Francesca decides t...",Specialist Lamont Johnson has built an effecti...,0,3,1,3,0
140,236,Time Without Pity,1956,Thriller,88,Great Britain,Joseph Losey,"Michael Redgrave, Ann Todd, Peter Cushing, Joa...",7.9,8.00,8.0,16,Alec Graham was sentenced to death for killing...,Emigrated to Great Britain after being blackli...,0,3,2,3,0
183,296,Strangers on a Train,1951,Thriller,96,United States,Alfred Hitchcock,"Farley Granger, Robert Walker, Ruth Roman, Leo...",8.4,8.66,8.0,258,Guy Haines is a successful tennis player with ...,"Patricia Highsmith's first novel, that of the ...",1,2,2,4,0
302,478,Gaslight,1944,Thriller,109,United States,George Cukor,"Ingrid Bergman, Charles Boyer, Joseph Cotten, ...",7.8,7.86,8.0,94,"Paula married Gregory, who long ago strangled ...","Nice ""gothic"" melodrama by George Cukor. The m...",2,4,3,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40950,216918,Aru otoko,2022,Thriller,121,Japan,Kei Ishikawa,"Satoshi Tsumabuki, Sakura Andô, Masataka Kubot...",7.3,7.00,8.0,3,Akira works as a lawyer and one day he meets a...,NaN,0,0,0,0,0
41118,220183,The Other Child,2022,Thriller,114,South Korea,Jin-young Kim,"Kim Min-Jae, Hyo-ju Park",5.3,3.00,8.0,3,The members of a family deeply likes the disap...,NaN,0,0,0,0,0
41200,221403,Anatomie d'une chute,2023,Thriller,151,France,Justine Triet,"Sandra Hüller, Samuel Theis, Swann Arlaud, Jeh...",7.3,7.00,8.0,4,"Samuel is found dead, buried in the snow outsi...",NaN,0,0,0,0,0
41218,221890,Ming On,2022,Thriller,109,Hong Kong,Soi Cheang,"Ka-Tung Lam, Charm Man Chan, Wing-Sze Ng, Lok ...",7.8,8.00,8.0,4,"A master of fortune teller (Gordon Lam), very ...",NaN,0,0,0,0,0
41246,223251,Twisted Nerve,1968,Thriller,112,Great Britain,Roy Boulting,"Hayley Mills, Hywel Bennett, Billie Whitelaw, ...",7.5,7.00,8.0,3,Martin Durnley (Hywel Bennett) is a twenty yea...,NaN,0,0,0,0,0

In [67]:
# Movies from a specific country
us_movies = df[df['country'] == 'United States']
us_movies

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
7,23,Dead-Bang,1989,Crime,109,United States,John Frankenheimer,"Don Johnson, Penelope Ann Miller, William Fors...",6.0,6.00,6.0,27,"In the throes of a double murder, Jerry Beck, ...",When it comes to talking about mysterious plot...,0,2,0,2,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41377,231044,Shelter,2023,Thriller,91,United States,Anthony Nardolillo,"Cam Gigandet, Jaina Lee Ortiz, Lisa Vidal, Car...",3.7,4.00,3.0,7,"Annabel, leader of a secret organization engag...",NaN,1,1,1,1,0
41382,231556,To End All War: Oppenheimer & the Atomic Bomb,2023,Documentary,87,United States,Christopher Cassel,"J. Robert Oppenheimer, Kai Bird, Ellen Bradbur...",6.6,5.00,8.0,8,"The arrogance, genius and determination of a m...",NaN,0,0,0,0,0
41384,232066,Hostage House,2021,Horror,85,United States,David Benullo,"Jennifer Taylor, Justin C. Schilling, Julia Te...",4.8,NaN,5.0,4,An ambitious real estate agent and his daughte...,NaN,0,0,0,0,0
41385,232101,Fear the Night,2023,Horror,92,United States,Neil LaBute,"Maggie Q, Ito Aghayere, Philip Burke, James Ca...",3.5,3.00,4.0,5,Tes is a veteran of the war in Iraq invited to...,NaN,0,0,0,0,0
41391,232755,Organ Trail,2023,Western,112,United States,Michael Patrick Jann,"Zoé De Grand Maison, Mather Zickel, Lisa LoCic...",5.0,5.50,5.0,8,The young abigale Archer is located alone in M...,NaN,0,0,0,0,0

## <b> Updating Rows and Columns </b>

**df.drop:**
The .drop() method in pandas is used to remove rows or columns from a DataFrame. Its primary purpose is to drop specified labels from rows or columns.

**Parameters:**

**labels:** The row or column labels to drop.

**axis:** Specifies whether the labels refer to rows (axis=0) or columns (axis=1). By default, it's 0 (rows).

**index or columns:** An alternative way to specify the labels to drop, instead of using the labels parameter. It is equivalent to specifying axis=0 (for index) or axis=1 (for columns).

**inplace:** If True, the operation is done in place, meaning it modifies the DataFrame directly and returns None. If False or not specified, it returns a new DataFrame with the specified labels dropped.

In [68]:
df.drop(labels='title',axis=1)

,filmtv_id,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [69]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

**Direct Assignment:**
Directly assign a value to a specific column or even a cell in a DataFrame.

In [70]:
df.at[0, 'year'] = 1983  # Changes the year of the first movie to 1983
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [71]:
df['new_column'] = 'default value'  # Adds a new column with all entries set to 'default value'
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,new_column
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,default value
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,default value
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,default value
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,default value
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,default value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,default value
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,default value
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,default value
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,default value
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,default value

In [72]:
df.drop(axis=1,labels='new_column',inplace=True)

In [74]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

**Using loc for Conditional Updates:**
loc can be used to update rows and columns based on a condition.

In [75]:
df.loc[df['year'] < 2000, 'classic'] = True  # Marks movies before 2000 as classic
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,classic
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,True
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,True
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,True
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,True
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,NaN
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,NaN
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,NaN
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,NaN
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,NaN

In [76]:
df.loc[df['avg_vote'] > 6, ['top_rated', 'must_watch']] = [True, True] # Modifying multiple columns using loc

In [77]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,description,notes,humor,rhythm,effort,tension,erotism,classic,top_rated,must_watch
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,True,True,True
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,True,True,True
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,True,NaN,NaN
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,True,True,True
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,NaN,NaN,NaN
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,NaN,NaN,NaN
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,NaN,NaN,NaN
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,NaN,NaN,NaN
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,NaN,NaN,NaN

**Using apply Function:**
The apply function allows you to apply a function along an axis of the DataFrame.

In [78]:
df['length_category'] = df['duration'].apply(lambda x: 'Long' if x > 120 else 'Short')
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,notes,humor,rhythm,effort,tension,erotism,classic,top_rated,must_watch,length_category
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"These are many small independent stories, whic...",3,3,0,0,0,True,True,True,Short
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,True,True,True,Short
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,True,NaN,NaN,Short
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,True,True,True,Short
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,Taken from the play by Armando Curcio that the...,3,1,1,0,0,True,NaN,NaN,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Freely taken from a true story.,0,0,0,0,0,NaN,NaN,NaN,Short
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,Bachelorette fare sequel (2021).,0,0,0,0,0,NaN,NaN,NaN,Short
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short

In [79]:
# Create a DataFrame with multiple Series
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
num_data = pd.DataFrame(data)

In [80]:
num_data

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [81]:
# Define a function to sum two Series
def sum_series(x, y):
    return x + y

# Apply the function on multiple Series using apply()
result = num_data.apply(lambda row: sum_series(row['A'], row['B']), axis=1)

# Print the result
print(result)

0    5
1    7
2    9
dtype: int64

**Updating Using map or replace:**
You can update a column based on a mapping dictionary or replace values.

In [82]:
df['genre'].map({'Drama': 'Drama Film', 'Comedy': 'Comedy Film'}) # Mapping existing values to new ones

0                NaN
1         Drama Film
2                NaN
3        Comedy Film
4        Comedy Film
            ...
41394            NaN
41395    Comedy Film
41396            NaN
41397            NaN
41398            NaN
Name: genre, Length: 41399, dtype: object

In [83]:
df['country'].replace('USA', 'United States', inplace=True) # Replacing specific values
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,notes,humor,rhythm,effort,tension,erotism,classic,top_rated,must_watch,length_category
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"These are many small independent stories, whic...",3,3,0,0,0,True,True,True,Short
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,True,True,True,Short
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,True,NaN,NaN,Short
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,True,True,True,Short
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,Taken from the play by Armando Curcio that the...,3,1,1,0,0,True,NaN,NaN,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Freely taken from a true story.,0,0,0,0,0,NaN,NaN,NaN,Short
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,Bachelorette fare sequel (2021).,0,0,0,0,0,NaN,NaN,NaN,Short
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short

**Adding New Columns Based on Calculations:**
You can create new columns based on calculations from existing columns.

In [84]:
df['title_year'] = df['title'] + " (" + df['year'].astype(str) + ")" # Creating a new column by combining existing columns
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,humor,rhythm,effort,tension,erotism,classic,top_rated,must_watch,length_category,title_year
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,3,3,0,0,0,True,True,True,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,2,0,True,True,True,Short,18 anni tra una settimana (1991)
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,2,1,0,0,True,NaN,NaN,Short,Ride a Wild Pony (1976)
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,2,2,0,1,2,True,True,True,Short,Diner (1982)
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,3,1,1,0,0,True,NaN,NaN,Short,A che servono questi quattrini? (1942)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,0,0,NaN,NaN,NaN,Short,Gold Digger Killer (2021)
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,0,0,NaN,NaN,NaN,Short,Addio al nubilato 2 (2023)
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,0,0,NaN,NaN,NaN,Short,Konferensen (2023)
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,0,0,NaN,NaN,NaN,Short,Ballelina (2023)
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,0,0,NaN,NaN,NaN,Short,Invitación a un Asesinato (2023)

**Using assign to Create Columns:**
assign helps you add new columns to a DataFrame in a functional style.

In [85]:
df = df.assign(
    is_older=lambda x: x['year'] < 2000,
    duration_hours=lambda x: x['duration'] / 60
) # Adding multiple new columns

In [86]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,classic,top_rated,must_watch,length_category,title_year,is_older,duration_hours
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,True,True,True,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,True,True,True,Short,18 anni tra una settimana (1991),True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,True,NaN,NaN,Short,Ride a Wild Pony (1976),True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,True,True,True,Short,Diner (1982),True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,True,NaN,NaN,Short,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Gold Digger Killer (2021),False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,NaN,NaN,NaN,Short,Addio al nubilato 2 (2023),False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Konferensen (2023),False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,NaN,NaN,NaN,Short,Ballelina (2023),False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Invitación a un Asesinato (2023),False,1.533333

# Changing the name of Index
Pandas allows you to rename the index of a DataFrame or Series, which can help in making the index more informative or aligning it with new data requirements.

**Renaming the Index of a DataFrame:**

In [87]:
df.index.names = ['movie_id']  # Renames the index to 'movie_id'
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,classic,top_rated,must_watch,length_category,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,True,True,True,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,True,True,True,Short,18 anni tra una settimana (1991),True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,True,NaN,NaN,Short,Ride a Wild Pony (1976),True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,True,True,True,Short,Diner (1982),True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,True,NaN,NaN,Short,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Gold Digger Killer (2021),False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,NaN,NaN,NaN,Short,Addio al nubilato 2 (2023),False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Konferensen (2023),False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,NaN,NaN,NaN,Short,Ballelina (2023),False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Invitación a un Asesinato (2023),False,1.533333

**Renaming Column Indexes:**

In [88]:
df.rename(columns={'year': 'release_year', 'title': 'movie_title'}, inplace=True)
df

,filmtv_id,movie_title,release_year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,classic,top_rated,must_watch,length_category,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,True,True,True,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,True,True,True,Short,18 anni tra una settimana (1991),True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,True,NaN,NaN,Short,Ride a Wild Pony (1976),True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,True,True,True,Short,Diner (1982),True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,True,NaN,NaN,Short,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Gold Digger Killer (2021),False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,NaN,NaN,NaN,Short,Addio al nubilato 2 (2023),False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Konferensen (2023),False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,NaN,NaN,NaN,Short,Ballelina (2023),False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Invitación a un Asesinato (2023),False,1.533333

## <b> Display Options </b>

In [89]:
# Set maximum number of rows and columns to display
pd.set_option('display.max_rows', 7)
pd.set_option('display.max_columns', 5)

In [90]:
df

,filmtv_id,movie_title,...,is_older,duration_hours
movie_id,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,...,True,1.266667
1,3,18 anni tra una settimana,...,True,1.633333
2,17,Ride a Wild Pony,...,True,1.516667
...,...,...,...,...,...
41396,232915,Konferensen,...,False,1.666667
41397,232919,Ballelina,...,False,1.533333
41398,232920,Invitación a un Asesinato,...,False,1.533333

In [91]:
# Reset Options
pd.reset_option('display')

In [92]:
df

,filmtv_id,movie_title,release_year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,classic,top_rated,must_watch,length_category,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,True,True,True,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,True,True,True,Short,18 anni tra una settimana (1991),True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,True,NaN,NaN,Short,Ride a Wild Pony (1976),True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,True,True,True,Short,Diner (1982),True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,True,NaN,NaN,Short,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Gold Digger Killer (2021),False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,NaN,NaN,NaN,Short,Addio al nubilato 2 (2023),False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Konferensen (2023),False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,NaN,NaN,NaN,Short,Ballelina (2023),False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,NaN,NaN,NaN,Short,Invitación a un Asesinato (2023),False,1.533333

## <b> Grouping Data: </b>

Grouping data is a powerful way to perform segment-wise analysis and break down the dataset into chunks based on some criteria.

In [93]:
genre_groups = df.groupby('genre')  # Groups the data by the 'genre' column
genre_groups

In [94]:
for genre, group_data in genre_groups:
    print(f"Genre: {genre}")
    print(group_data)
    print()

Genre: Action
          filmtv_id           movie_title  release_year   genre  duration  \
movie_id
15               38          Mr. Majestyk          1974  Action       105
16               45          Warning Sign          1985  Action        99
109             193           Airport '77          1977  Action       110
342             530   Wings of the Apache          1990  Action        86
369             574  Geheimcode Wildgänse          1985  Action        93
...             ...                   ...           ...     ...       ...
41308        225561    Tin joek yau ching          1990  Action        87
41314        226116          Blood & Gold          2023  Action       100
41337        228408          Kung Fu Girl          2021  Action        98
41343        229097               Hit Man          2023  Action       113
41378        231061            Sentinelle          2023  Action        99

                country                         directors  \
movie_id
15        United States                 Richard Fleischer
16        United States                       Hal Barwood
109       United States                     Jerry Jameson
342       United States                       David Green
369               Italy                Antonio Margheriti
...                 ...                               ...
41308         Hong Kong                        Benny Chan
41314           Germany                   Peter Thorwarth
41337     United States           Devon Downs, Kenny Gage
41343     United States                 Richard Linklater
41378            France  Hugo Benamozig, David Caviglioli

                                                     actors  avg_vote  \
movie_id
15        Charles Bronson, Linda Cristal, Al Lettieri, L...       6.2
16        Sam Waterston, Kathleen Quinlan, Yaphet Kotto,...       4.8
109       Jack Lemmon, James Stewart, Lee Grant, Brenda ...       4.7
342       Nicolas Cage, Sean Young, Tommy Lee Jones, Dal...       4.6
369       Lewis Collins, Lee Van Cleef, Ernest Borgnine,...       4.9
...                                                     ...       ...
41308     Andy Lau, Chien-lien Wu, Man-Tat Ng, Kwong-Leu...       7.5
41314     Jördis Triebel, Alexander Scheer, Robert Maase...       6.1
41337     Danny Kwok-Kwan Chan, Yixi Tao, Shuting Li, Xi...       4.5
41343     Adria Arjona, Glen Powell, Retta, Austin Ameli...       7.1
41378     Jonathan Cohen, Emmanuelle Bercot, Raphaël Que...       4.0

          critics_vote  ...  effort  tension erotism classic  top_rated  \
movie_id                ...
15                5.71  ...       3        3       0    True       True
16                4.00  ...       1        1       0    True        NaN
109               3.33  ...       0        1       0    True        NaN
342               4.00  ...       0        1       1    True        NaN
369               3.50  ...       0        2       0    True        NaN
...                ...  ...     ...      ...     ...     ...        ...
41308             7.00  ...       0        0       0    True       True
41314             5.67  ...       0        0       0     NaN       True
41337              NaN  ...       0        0       0     NaN        NaN
41343             7.00  ...       0        0       0     NaN       True
41378              NaN  ...       0        0       0     NaN        NaN

          must_watch  length_category                   title_year  is_older  \
movie_id
15              True            Short          Mr. Majestyk (1974)      True
16               NaN            Short          Warning Sign (1985)      True
109              NaN            Short           Airport '77 (1977)      True
342              NaN            Short   Wings of the Apache (1990)      True
369              NaN            Short  Geheimcode Wildgänse (1985)      True
...              ...              ...                          ...       ...
41308           True            Short    Tin joek yau ching (1990)      True
41314           True            Short          Blood & Gold (2023)     False
41337            NaN            Short          Kung Fu Girl (2021)     False
41343           True            Short               Hit Man (2023)     False
41378            NaN            Short            Sentinelle (2023)     False

         duration_hours
movie_id
15             1.750000
16             1.650000
109            1.833333
342            1.433333
369            1.550000
...                 ...
41308          1.450000
41314          1.666667
41337          1.633333
41343          1.883333
41378          1.650000

[2155 rows x 26 columns]

Genre: Adventure
          filmtv_id                       movie_title  release_year  \
movie_id
10               30         A Ghentar si muore facile          1968
20               53                A qualsiasi prezzo          1968
33               74                          The Deep          1977
82              145                    Africa Express          1975
83              146               Africa sotto i mari          1952
...             ...                               ...           ...
41222        222074                   We Have a Ghost          2023
41230        222398          Tremors: Shrieker Island          2020
41274        224588             Knights of the Zodiac          2023
41293        225497  Coast Guard Malaysia: Ops Helang          2023
41330        227960                     Hidden Strike          2023

              genre  duration                        country  \
movie_id
10        Adventure       101                          Italy
20        Adventure        94                          Italy
33        Adventure       130                  United States
82        Adventure        95                          Italy
83        Adventure        95                          Italy
...             ...       ...                            ...
41222     Adventure       126                  United States
41230     Adventure       103                  United States
41274     Adventure       112  Japan, Hungary, United States
41293     Adventure        90                       Malaysia
41330     Adventure       102           China, United States

                   directors  \
movie_id
10            Leon Klimovsky
20           Emilio Miraglia
33               Peter Yates
82              Michele Lupo
83         Giovanni Roccardi
...                      ...
41222     Christopher Landon
41230       Don Michael Paul
41274        Tomasz Baginski
41293             Pitt Hanif
41330            Scott Waugh

                                                     actors  avg_vote  \
movie_id
10        George Hilton, Ennio Girolami, Marta Padovan, ...       4.8
20        Walter Pidgeon, Ira Fürstenberg, Klaus Kinski,...       3.8
33        Nick Nolte, Jacqueline Bisset, Robert Shaw, El...       5.3
82        Giuliano Gemma, Ursula Andress, Jack Palance, ...       5.1
83        Sophia Loren, Stephen Barclay, Umberto Melnati...       4.1
...                                                     ...       ...
41222     Jennifer Coolidge, David Harbour, Anthony Mack...       6.2
41230     Michael Gross, Jon Heder, Richard Brake, Carol...       5.6
41274     Famke Janssen, Sean Bean, Madison Iseman, Mark...       3.4
41293     Saharul Ridzwan, Julia Farhana Marin, Sabri Yu...       3.5
41330     Jackie Chan, John Cena, Pilou Asbæk, Rachael H...       6.0

          critics_vote  ...  effort  tension erotism classic  top_rated  \
movie_id                ...
10                4.50  ...       0        1       0    True        NaN
20                4.00  ...       0        1       1    True        NaN
33                4.88  ...       1        2       1    True        NaN
82                5.50  ...       0        1       1    True        NaN
83                4.00  ...       0        1       2    True        NaN
...                ...  ...     ...      ...     ...     ...        ...
41222             6.00  ...       0        0       0     NaN       True
41230             5.00  ...       0        0       0     NaN        NaN
41274             3.00  ...       0        0       0     NaN        NaN
41293             3.00  ...       0        0       0     NaN        NaN
41330              NaN  ...       0        0       0     NaN        NaN

          must_watch  length_category  \
movie_id
10               NaN            Short
20               NaN            Short
33               NaN             Long
82               NaN            Short
83               NaN            Short
...              ...              ...
41222           True             Long
41230            NaN            Short
41274            NaN            Short
41293            NaN            Short
41330            NaN            Short

                                       title_year  is_older duration_hours
movie_id
10               A Ghentar si muore facile (1968)      True       1.683333
20                      A qualsiasi prezzo (1968)      True       1.566667
33                                The Deep (1977)      True       2.166667
82                          Africa Express (1975)      True       1.583333
83                     Africa sotto i mari (1952)      True       1.583333
...                                           ...       ...            ...
41222                      We Have a Ghost (2023)     False       2.100000
41230             Tremors: Shrieker Island (2020)     False       1.716667
41274                Knights of the Zodiac (2023)     False       1.866667
41293     Coast Guard Malaysia: Ops Helang (2023)     False       1.500000
41330                        Hidden Strike (2023)     False       1.700000

[1524 rows x 26 columns]

Genre: Animation
          filmtv_id                                  movie_title  \
movie_id
0                 2  Bugs Bunny's Third Movie: 1001 Rabbit Tales
159             260                         The Land Before Time
167             271                           Allegro non troppo
435             679                 Asterix et le coup de menhir
715            1093                           The Secret Of Nimh
...             ...                                          ...
41256        223768  Teenage Mutant Ninja Turtles: Mutant Mayhem
41257        223769                          The First Slam Dunk
41266        224224                 Ruby Gillman, Teenage Kraken
41348        229395                  Lonely Castle in the Mirror
41363        229825                                      Invelle

          release_year      genre  duration        country  \
movie_id
0                 1983  Animation        76  United States
159               1988  Animation        79  United States
167               1977  Animation        85          Italy
435               1989  Animation        81         France
715               1982  Animation        82  United States
...                ...        ...       ...            ...
41256             2023  Animation        99  United States
41257             2022  Animation       124          Japan
41266             2023  Animation        91  United States
41348             2022  Animation       116          Japan
41363             2023  Animation        96          Italy

                                     directors  \
movie_id
0         David Detiege, Art Davis, Bill Perez
159                                  Don Bluth
167                             Bruno Bozzetto
435                           Philippe Grimond
715                                  Don Bluth
...                                        ...
41256                  Jeff Rowe, Kyler Spears
41257           Takehiko Inoue, Yasuyuki Ebara
41266                             Kirk DeMicco
41348          Keiichi Hara, Takakazu Nagatomo
41363                             Simone Massi

                                                     actors  avg_vote  \
movie_id
0                                                       NaN       7.7
159                                                     NaN       7.4
167       Maurizio Nichetti, Maurizio Micheli, Maria Lui...       7.6
435                                                     NaN       6.8
715                                                     NaN       8.2
...                                                     ...       ...
41256                                                   NaN       6.4
41257                                                   NaN       8.0
41266                                                   NaN       6.0
41348                                                   NaN       6.7
41363                                                   NaN       9.0

          critics_vote  ...  effort  tension erotism classic  top_rated  \
movie_id                ...
0                 8.00  ...       0        0       0    True       True
159               7.50  ...       0        1       0    True       True
167               7.71  ...       2        0       0    True       True
435               6.67  ...       0        0       0    True       True
715               8.50  ...       0        2       0    True       True
...                ...  ...     ...      ...     ...     ...        ...
41256             6.50  ...       0        0       0     NaN       True
41257              NaN  ...       0        0       0     NaN       True
41266             7.00  ...       0        0       0     NaN        NaN
41348             6.50  ...       1        1       1     NaN       True
41363             8.50  ...       0        0       0     NaN       True

          must_watch  length_category  \
movie_id
0               True            Short
159             True            Short
167             True            Short
435             True            Short
715             True            Short
...              ...              ...
41256           True            Short
41257           True             Long
41266            NaN            Short
41348           True            Short
41363           True            Short

                                                 title_year  is_older  \
movie_id
0         Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...      True
159                             The Land Before Time (1988)      True
167                               Allegro non troppo (1977)      True
435                     Asterix et le coup de menhir (1989)      True
715                               The Secret Of Nimh (1982)      True
...                                                     ...       ...
41256     Teenage Mutant Ninja Turtles: Mutant Mayhem (2...     False
41257                            The First Slam Dunk (2022)     False
41266                   Ruby Gillman, Teenage Kraken (2023)     False
41348                    Lonely Castle in the Mirror (2022)     False
41363                                        Invelle (2023)     False

         duration_hours
movie_id
0              1.266667
159            1.316667
167            1.416667
435            1.350000
715            1.366667
...                 ...
41256          1.650000
41257          2.066667
41266          1.516667
41348          1.933333
41363          1.600000

[1076 rows x 26 columns]

Genre: Biblical
          filmtv_id                         movie_title  release_year  \
movie_id
615             942                             Ben Hur          1959
1419           2119                The Ten Commandments          1956
1697           2531                     Erode il Grande          1958
2114           3151                 Giuditta e Oloferne          1958
2124           3167       Giuseppe venduto dai fratelli          1961
2863           4274                           Il Messia          1975
3563           5347        The Greatest Story Ever Told          1965
3896           5854                   The King of Kings          1961
4453           6677                 La spada e la croce          1959
4549           6836                   The Story of Ruth          1960
4919           7372                            The Robe          1953
5940           9031                   Solomon and Sheba          1959
6826          10368                       David e Golia          1959
8392          12762  Genesi - La Creazione e il Diluvio          1994
8434          12825                       Ester e il re          1960
10942         16849                              Esther          1985
11573         17935                        Il quarto re          1997
12595         19554                     Maria Maddalena          2000
13469         21090                               Giuda          2000
13493         21135                             Tommaso          2001
13955         21910                Giuseppe di Nazareth          1999
15262         24080          San Giovanni. L'Apocalisse          2002
16603         26238                          Noah's Ark          1999
16660         26341           The Passion of the Christ          2004
20557         35707                    Gesù di Nazareth          1977
24155         42350                    Viaggiu dulurusu          1992
24204         42430                   The King of Kings          1927
27294         51072                              Salome          1922
27423         51481                    Maria di Nazaret          2012
28105         54251                             Ben Hur          2010
28470         56046                            Jeremiah          1998
28996         58832                          San Pietro          2005
29311         60587                             Solomon          1997
29414         61169                   Paul the Apostole          2000
30100         65370                          Son of God          2014
31873         76154                  Samson and Delilah          1996
31902         76434                               David          1997
35781        150491                              Samson          2018

             genre  duration  \
movie_id
615       Biblical       212
1419      Biblical       220
1697      Biblical        95
2114      Biblical        94
2124      Biblical       102
2863      Biblical       140
3563      Biblical       200
3896      Biblical       168
4453      Biblical       106
4549      Biblical       132
4919      Biblical       135
5940      Biblical       120
6826      Biblical       113
8392      Biblical       101
8434      Biblical       109
10942     Biblical        90
11573     Biblical        90
12595     Biblical        93
13469     Biblical        90
13493     Biblical        90
13955     Biblical        96
15262     Biblical       130
16603     Biblical       130
16660     Biblical       126
20557     Biblical       371
24155     Biblical        41
24204     Biblical       112
27294     Biblical        72
27423     Biblical       200
28105     Biblical       180
28470     Biblical        90
28996     Biblical       200
29311     Biblical       180
29414     Biblical       170
30100     Biblical       138
31873     Biblical       172
31902     Biblical       190
35781     Biblical       116

                                                    country  \
movie_id
615                                           United States
1419                                          United States
1697                                                  Italy
2114                                                  Italy
2124                                      Italy, Yugoslavia
2863                                          Italy, France
3563                                          United States
3896                                          United States
4453                                                  Italy
4549                                          United States
4919                                          United States
5940                                          United States
6826                                                  Italy

In [95]:
year_genre_groups = df.groupby(['release_year', 'genre'])  # Groups by year and genre

In [96]:
year_genre_groups

# Aggregation

After grouping, you might want to perform aggregation operations like sum, mean, count, etc., to summarize the data.

In [97]:
# Simple Aggregation - Calculating the Average
avg_duration_by_genre = df.groupby('genre')['duration'].mean()  # Average duration per genre
print(avg_duration_by_genre)

genre
Action             101.682599
Adventure          102.870079
Animation           88.925651
Biblical           137.210526
Biography          120.602920
Comedy              97.881409
Crime               98.939914
Documentary         92.641638
Drama              105.271266
Erotico             90.893617
Fantasy            105.612326
Gangster           117.803571
Grotesque           99.851852
History            127.159420
Horror              92.603867
Musical            106.240654
Mythology           97.969697
Mélo               107.836538
Noir                98.428571
Romantic            94.778571
Sci-Fi             102.097238
Short Movie        210.500000
Sperimental         97.716049
Sport               95.428571
Spy                105.333333
Stand-up Comedy     73.000000
Super-hero         121.855422
Thriller            97.957849
War                111.306173
Western             95.800175
Name: duration, dtype: float64

In [98]:
# Multiple Aggregations on a Single Column
stats_by_genre = df.groupby('genre')['avg_vote'].agg([np.mean, np.std, np.min, np.max])
print(stats_by_genre)

                     mean       std  min   max
genre
Action           5.123898  1.399433  1.0   9.0
Adventure        5.545866  1.324040  1.4   9.3
Animation        6.118030  1.281681  1.6   9.3
Biblical         5.184211  1.273753  2.9   8.2
Biography        5.949051  1.208300  1.0  10.0
Comedy           5.482645  1.355306  1.0  10.0
Crime            6.142918  1.167942  2.7   8.8
Documentary      6.564749  1.180058  1.0  10.0
Drama            6.292677  1.302034  1.0  10.0
Erotico          4.052766  1.323337  1.0   7.9
Fantasy          5.486282  1.322481  1.3   9.4
Gangster         6.614286  1.383333  2.5   9.0
Grotesque        6.458848  1.250535  2.3   9.1
History          5.887681  1.245398  2.7   8.8
Horror           5.225874  1.301247  1.3   9.1
Musical          6.016121  1.474926  1.8   9.0
Mythology        4.631818  1.298183  2.2   8.0
Mélo             6.715385  1.256731  3.6   8.6
Noir             6.985294  1.104915  3.4   9.5
Romantic         4.883367  1.532141  1.0   8.8
Sci-Fi           5.484309  1.365001  1.4   9.2
Short Movie      6.800000  0.843801  5.3   7.7
Sperimental      6.547531  1.170454  2.0   9.0
Sport            5.228571  1.879463  3.0   7.5
Spy              5.769167  1.399898  2.0   8.8
Stand-up Comedy  7.325000  0.793200  6.8   8.5
Super-hero       5.833735  1.032671  2.3   7.5
Thriller         5.530586  1.264825  1.0   9.3
War              6.293086  1.301066  1.7   9.3
Western          5.744590  1.306447  1.5   8.9

In [99]:
# Different Aggregations for Different Columns
complex_aggregation = df.groupby('genre').agg({
    'duration': np.mean,  # average duration
    'avg_vote': [np.min, np.max],  # min and max average votes
    'public_vote': 'sum'  # total of public votes
})

In [100]:
complex_aggregation

                   duration avg_vote       public_vote
                       mean      min   max         sum
genre
Action           101.682599      1.0   9.0     11369.0
Adventure        102.870079      1.4   9.3      8747.0
Animation         88.925651      1.6   9.3      6639.0
Biblical         137.210526      2.9   8.2       202.0
Biography        120.602920      1.0  10.0      4136.0
Comedy            97.881409      1.0  10.0     51634.0
Crime             98.939914      2.7   8.8      2953.0
Documentary       92.641638      1.0  10.0     13371.0
Drama            105.271266      1.0  10.0     76234.0
Erotico           90.893617      1.0   7.9       981.0
Fantasy          105.612326      1.3   9.4      2830.0
Gangster         117.803571      2.5   9.0       378.0
Grotesque         99.851852      2.3   9.1      1578.0
History          127.159420      2.7   8.8       823.0
Horror            92.603867      1.3   9.1     12917.0
Musical          106.240654      1.8   9.0      2647.0
Mythology         97.969697      2.2   8.0       338.0
Mélo             107.836538      3.6   8.6       705.0
Noir              98.428571      3.4   9.5      1640.0
Romantic          94.778571      1.0   8.8      4906.0
Sci-Fi           102.097238      1.4   9.2      5064.0
Short Movie      210.500000      5.3   7.7        41.0
Sperimental       97.716049      2.0   9.0      1018.0
Sport             95.428571      3.0   7.5        37.0
Spy              105.333333      2.0   8.8      1406.0
Stand-up Comedy   73.000000      6.8   8.5        32.0
Super-hero       121.855422      2.3   7.5       488.0
Thriller          97.957849      1.0   9.3     21048.0
War              111.306173      1.7   9.3      2596.0
Western           95.800175      1.5   8.9      6739.0

**Aggregating Without Grouping:**
Sometimes, you may want to perform aggregations without the need to group the data.

In [102]:
# Overall Summary Statistics
overall_stats = df[['duration', 'avg_vote']].describe()
overall_stats

           duration      avg_vote
count  41399.000000  41399.000000
mean     100.537163      5.801522
std       27.260962      1.403861
min       41.000000      1.000000
25%       90.000000      4.800000
50%       96.000000      5.900000
75%      107.000000      6.900000
max     1525.000000     10.000000

**df.count():** This method returns the number of non-null values in each DataFrame column. It can be used to count the number of non-null values in each column individually.

In [103]:
# Create a DataFrame
data = {'A': [1, 2, None], 'B': [4, None, 6], 'C': [5, 8, 9]}
data_df = pd.DataFrame(data)

# Count non-null values in each column
counts = data_df.count()
print(counts)

A    2
B    2
C    3
dtype: int64

**df.value_counts():** This method returns the frequency counts of unique values in a Series. It is typically used on a single column of the DataFrame and is useful for analyzing the distribution of values within that column.

In [104]:
# Value Counts
df['movie_title'].value_counts()

movie_title
Les Vampires                 10
Pinocchio                     8
Riget II                      6
Dr. Jekyll and Mr. Hyde       5
Sibiriada                     5
                             ..
Farelavita                    1
A, B, C... Manhattan          1
Parfait amour!                1
A Season for Miracles         1
Invitación a un Asesinato     1
Name: count, Length: 39531, dtype: int64

**Custom Aggregation Functions:**
Pandas allows you to define and use custom aggregation functions for more specific data analysis needs.

In [105]:
# Using a Custom Function for Aggregation
def range_func(series):
    return series.max() - series.min()

range_by_genre = df.groupby('genre')['duration'].agg(range_func)  # Range of durations by genre
range_by_genre

genre
Action              197
Adventure           355
Animation          1129
Biblical            330
Biography           267
Comedy              558
Crime               135
Documentary         859
Drama              1484
Erotico              61
Fantasy             202
Gangster            245
Grotesque           236
History             560
Horror              213
Musical             247
Mythology           104
Mélo                151
Noir                110
Romantic            150
Sci-Fi              259
Short Movie         487
Sperimental         774
Sport                34
Spy                 115
Stand-up Comedy      27
Super-hero          101
Thriller            550
War                 655
Western             145
Name: duration, dtype: int64

**Renaming Grouped Aggregation Results:**
It is often useful to rename the results of aggregations for clarity or further analysis.

In [106]:
# Renaming Aggregation Results
renamed_aggregations = df.groupby('genre')['avg_vote'].agg([
    ('Average Rating', 'mean'),  # Renames the mean result to 'Average Rating'
    ('Rating Standard Deviation', 'std')  # Renames the std result to 'Rating Standard Deviation'
])
renamed_aggregations

                 Average Rating  Rating Standard Deviation
genre
Action                 5.123898                   1.399433
Adventure              5.545866                   1.324040
Animation              6.118030                   1.281681
Biblical               5.184211                   1.273753
Biography              5.949051                   1.208300
Comedy                 5.482645                   1.355306
Crime                  6.142918                   1.167942
Documentary            6.564749                   1.180058
Drama                  6.292677                   1.302034
Erotico                4.052766                   1.323337
Fantasy                5.486282                   1.322481
Gangster               6.614286                   1.383333
Grotesque              6.458848                   1.250535
History                5.887681                   1.245398
Horror                 5.225874                   1.301247
Musical                6.016121                   1.474926
Mythology              4.631818                   1.298183
Mélo                   6.715385                   1.256731
Noir                   6.985294                   1.104915
Romantic               4.883367                   1.532141
Sci-Fi                 5.484309                   1.365001
Short Movie            6.800000                   0.843801
Sperimental            6.547531                   1.170454
Sport                  5.228571                   1.879463
Spy                    5.769167                   1.399898
Stand-up Comedy        7.325000                   0.793200
Super-hero             5.833735                   1.032671
Thriller               5.530586                   1.264825
War                    6.293086                   1.301066
Western                5.744590                   1.306447